create table cliente (
	cod_cliente INT PRIMARY KEY,
	nome VARCHAR(50),
	sexo VARCHAR(50),
	dt_nascimento DATE,
	bairro VARCHAR(23)
);
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (1, 'Lesly Ygoe', 'F', '1971-01-15', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (2, 'Sophie McGinney', 'F', '1995-12-30', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (3, 'Giavani Minigo', 'M', '1996-10-23', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (4, 'Ignacio Crehan', 'M', '1985-06-29', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (5, 'Neil Muehle', 'M', '1983-09-10', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (6, 'Brandice Galloway', 'F', '1997-06-25', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (7, 'Petronella Habbeshaw', 'F', '1979-12-04', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (8, 'Latrina Lamcken', 'F', '1967-06-20', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (9, 'Jeramey Breffit', 'M', '1995-01-11', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (10, 'Anjela Sidgwick', 'F', '1992-09-15', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (11, 'Saundra Dahlman', 'F', '1987-09-17', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (12, 'Nathanial Bucklee', 'M', '1987-03-12', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (13, 'Erinna Rizzini', 'F', '1964-02-01', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (14, 'Arabela Streat', 'F', '1962-09-07', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (15, 'Wood Blomfield', 'M', '1988-08-03', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (16, 'Erna Chelsom', 'F', '2000-07-13', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (17, 'Karen Abden', 'F', '1993-02-19', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (18, 'Lynnet Goroni', 'F', '1986-02-03', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (19, 'Bentlee Liffe', 'M', '1967-06-07', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (20, 'Essa Ghiron', 'F', '1964-07-07', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (21, 'Marysa Kock', 'F', '1960-06-01', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (22, 'Nahum Stannah', 'M', '1975-03-24', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (23, 'Amitie Farron', 'F', '1980-04-05', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (24, 'Zonnya Curthoys', 'F', '1985-12-17', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (25, 'Willey Picard', 'M', '1968-02-25', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (26, 'Mick De Mitris', 'M', '2002-12-19', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (27, 'Cesaro Menaul', 'M', '1993-12-13', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (28, 'Hewe Pennone', 'M', '1997-12-31', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (29, 'Wilek Shout', 'M', '1969-11-29', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (30, 'Kari Borgne', 'F', '1995-09-03', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (31, 'Grant De Andreis', 'M', '1986-02-26', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (32, 'Correna Constantine', 'F', '1968-03-02', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (33, 'Cyrille Timlin', 'M', '1996-04-16', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (34, 'Rasla Lunny', 'F', '1984-12-28', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (35, 'Ricki Brudenell', 'M', '1964-01-31', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (36, 'Charis Shiers', 'F', '1992-02-25', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (37, 'Merna Sarll', 'F', '1994-11-16', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (38, 'Kurt Anfossi', 'M', '1984-12-06', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (39, 'Monika Walkley', 'F', '1960-04-23', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (40, 'Durante Llorens', 'M', '1974-08-16', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (41, 'Ondrea Hinckley', 'F', '1970-11-24', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (42, 'Bendicty Baudoux', 'M', '1980-02-22', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (43, 'Kelcey Cridge', 'F', '1997-04-16', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (44, 'Seymour Bourdon', 'M', '1987-11-20', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (45, 'Andy Shuter', 'M', '2001-08-03', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (46, 'Hasty Gibson', 'M', '1984-08-30', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (47, 'Brandtr Filov', 'M', '1972-12-12', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (48, 'Cash Southerns', 'M', '1974-12-30', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (49, 'Karel Chesters', 'M', '1977-09-27', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (50, 'Dirk Brusby', 'M', '2002-02-01', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (51, 'Latrina Sproson', 'F', '1998-08-18', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (52, 'Jaimie Skough', 'F', '1963-06-01', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (53, 'Marta Blackmore', 'F', '1962-01-23', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (54, 'Pris Lacknor', 'F', '1983-07-11', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (55, 'Bengt Ludvigsen', 'M', '1978-10-10', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (56, 'Fowler Cud', 'M', '2002-11-15', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (57, 'Sophia Rudge', 'F', '1976-02-25', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (58, 'Kippie Lampl', 'M', '2001-04-30', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (59, 'Immanuel Darko', 'M', '2002-12-17', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (60, 'Consuelo Berzon', 'F', '1980-11-30', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (61, 'Victor Pirson', 'M', '1975-10-03', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (62, 'Dede Pratley', 'F', '1996-04-13', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (63, 'Alessandra Ramshay', 'F', '1970-06-29', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (64, 'Henriette Lauderdale', 'F', '1985-01-08', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (65, 'Hank Kerkham', 'M', '1980-09-15', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (66, 'Vilma Braunds', 'F', '1985-10-15', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (67, 'Benjamin Grabham', 'M', '1962-04-06', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (68, 'Baillie Hatwells', 'M', '1965-07-28', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (69, 'Gilligan Loomis', 'F', '1982-02-06', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (70, 'Chaddy Mistry', 'M', '1961-05-26', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (71, 'Berne Do Rosario', 'M', '1983-07-18', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (72, 'Lucille Tessier', 'F', '1977-01-30', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (73, 'Susanetta Delmonti', 'F', '1969-05-15', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (74, 'Tabbie Lakey', 'F', '2002-06-11', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (75, 'Ilyssa D''Ambrogio', 'F', '1993-02-22', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (76, 'Georgeta Casemore', 'F', '1995-11-05', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (77, 'Griz Bandey', 'M', '1994-11-13', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (78, 'Lorry Cranham', 'F', '1961-08-25', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (79, 'Wit Ephson', 'M', '1980-06-23', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (80, 'Kathrine Beric', 'F', '1987-01-25', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (81, 'Geraldine Nemchinov', 'F', '1993-09-29', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (82, 'Ardelia Gymlett', 'F', '1969-10-04', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (83, 'Shurlock Dragge', 'M', '1964-09-11', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (84, 'Billi Eslinger', 'F', '1963-09-16', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (85, 'Marilyn Wickes', 'F', '1981-04-15', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (86, 'Madeleine Pedlingham', 'F', '1984-07-21', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (87, 'Veronica Manus', 'F', '2000-08-30', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (88, 'Quill Gwalter', 'M', '1984-10-30', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (89, 'Hebert Cowndley', 'M', '1974-06-03', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (90, 'Theodosia Mounter', 'F', '1998-12-11', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (91, 'Doris Hatchette', 'F', '1986-01-04', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (92, 'Abner Swiffen', 'M', '1993-09-11', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (93, 'Chev Bathoe', 'M', '1987-09-20', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (94, 'Georgetta Ettles', 'F', '2001-04-24', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (95, 'Archibaldo Norwell', 'M', '1994-02-01', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (96, 'Christophe Charrier', 'M', '1975-12-03', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (97, 'Dorita Bowstead', 'F', '1972-06-22', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (98, 'Paxton Ivimy', 'M', '1960-01-20', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (99, 'Ciro Cordery', 'M', '2002-04-02', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (100, 'Tobey Kember', 'F', '1974-06-20', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (101, 'Darb Beckhurst', 'M', '1968-05-08', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (102, 'Lavinie Whiteson', 'F', '1989-01-09', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (103, 'Anetta Abdee', 'F', '1970-05-23', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (104, 'Jacquelynn Curnokk', 'F', '1978-10-29', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (105, 'Latisha Guierre', 'F', '1985-12-24', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (106, 'Ole Blenkinsop', 'M', '1978-10-27', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (107, 'Ebeneser Etherson', 'M', '1997-03-21', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (108, 'Redford Sanbrook', 'M', '1980-03-25', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (109, 'Kassi Laweles', 'F', '1965-04-05', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (110, 'Vite Pashba', 'M', '1993-03-12', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (111, 'Winnah Finlayson', 'F', '1964-02-27', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (112, 'Tan Kondratowicz', 'M', '1960-07-17', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (113, 'Nealson Gumbley', 'M', '1993-06-22', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (114, 'Robby Fleetwood', 'M', '1983-03-04', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (115, 'Rana Rangle', 'F', '1966-06-04', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (116, 'Davey Philcox', 'M', '1962-12-28', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (117, 'Ailee Botha', 'F', '1990-01-29', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (118, 'Rebeca Jury', 'F', '2001-03-25', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (119, 'Terrance Boggas', 'M', '1997-08-02', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (120, 'Marty Dickerline', 'F', '1984-05-03', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (121, 'Jacynth Cruise', 'F', '1978-06-19', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (122, 'Lucas Slinn', 'M', '1998-05-07', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (123, 'Alikee Boobier', 'F', '1998-06-29', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (124, 'Mariya Raynor', 'F', '1989-04-23', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (125, 'Domingo Hale', 'M', '1983-09-28', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (126, 'Tammara Graveston', 'F', '1981-11-16', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (127, 'Starlin Spaule', 'F', '1973-01-14', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (128, 'Wiley Gerrens', 'M', '1981-03-09', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (129, 'Carolyn Dollimore', 'F', '1980-12-18', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (130, 'Milena Tiffany', 'F', '1966-06-15', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (131, 'Ainslee Muehler', 'F', '1975-04-09', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (132, 'Vale Downgate', 'M', '1977-07-22', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (133, 'Kurt Kinker', 'M', '1990-12-10', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (134, 'Dani Espadate', 'F', '1990-09-25', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (135, 'Delphine Marham', 'F', '1997-03-28', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (136, 'Lynnelle Swalough', 'F', '1965-01-13', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (137, 'Riki Arrighi', 'F', '1981-04-18', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (138, 'Elizabeth Pillman', 'F', '2001-02-14', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (139, 'Clarence Quinnelly', 'M', '1968-09-29', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (140, 'Elliot Barthelme', 'M', '1997-09-25', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (141, 'Valle Mardee', 'M', '1973-06-08', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (142, 'Caleb Leall', 'M', '1979-06-12', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (143, 'Marylin Kershow', 'F', '2001-12-06', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (144, 'Terrance MacNess', 'M', '1976-11-18', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (145, 'Benjamen Mathan', 'M', '1970-09-07', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (146, 'Ilyse Hardy', 'F', '1989-09-01', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (147, 'Virgina Muggach', 'F', '1962-08-06', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (148, 'Ania Hockell', 'F', '1988-10-26', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (149, 'Fraze Haller', 'M', '1991-11-11', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (150, 'Valaree Shears', 'F', '1961-08-26', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (151, 'Killian Hiddersley', 'M', '2001-05-22', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (152, 'Jayson Phoenix', 'M', '1973-05-23', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (153, 'Monte Lannon', 'M', '1998-01-06', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (154, 'Stanton Baddeley', 'M', '1981-03-05', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (155, 'Alberto Baptiste', 'M', '1997-01-16', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (156, 'Emily Coupland', 'F', '1965-09-08', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (157, 'Eartha Kitchingham', 'F', '1996-03-27', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (158, 'Hurleigh Spiby', 'M', '1991-06-22', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (159, 'Thekla Caesman', 'F', '1969-07-18', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (160, 'Florette Djorevic', 'F', '1967-01-31', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (161, 'Noe Truluck', 'M', '1993-04-21', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (162, 'Hollie Atwater', 'F', '1968-07-24', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (163, 'Maris Gask', 'F', '1989-09-24', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (164, 'Aloysia Van der Kruis', 'F', '1983-08-07', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (165, 'Marquita Barrass', 'F', '1987-06-14', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (166, 'Niven Corey', 'M', '1962-11-08', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (167, 'Breena Colling', 'F', '1991-12-12', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (168, 'Phineas Giddy', 'M', '2002-02-26', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (169, 'Camile Laux', 'F', '1985-06-30', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (170, 'Mersey Lapham', 'F', '1998-04-01', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (171, 'Dael Edsall', 'F', '1982-08-19', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (172, 'Gun Coaster', 'M', '1960-01-30', 'Vila São Luiz');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (173, 'Dehlia Pichmann', 'F', '1983-07-26', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (174, 'Sorcha Glawsop', 'F', '1972-01-07', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (175, 'Jeanine Dobbson', 'F', '1982-04-24', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (176, 'Cheri Coggles', 'F', '1965-03-09', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (177, 'Galven Yeoland', 'M', '1986-09-12', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (178, 'Elysia Wahner', 'F', '1988-12-17', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (179, 'Adolphus Loughnan', 'M', '1994-05-28', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (180, 'Lamond Heams', 'M', '1994-01-23', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (181, 'Daffi Aronstein', 'F', '1988-03-09', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (182, 'Sigismund Derycot', 'M', '1986-05-05', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (183, 'Rickie Lamperti', 'M', '1995-09-09', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (184, 'Garrard Tiffany', 'M', '1962-04-03', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (185, 'Shannan MacCaffery', 'M', '1960-11-01', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (186, 'Bevan Vasechkin', 'M', '1967-08-18', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (187, 'Sydelle Collymore', 'F', '1994-06-04', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (188, 'Kristin Pic', 'F', '1968-10-02', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (189, 'Melisande Trodden', 'F', '1971-06-10', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (190, 'Alaric Rasp', 'M', '1981-09-20', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (191, 'Lek Hunton', 'M', '1961-10-16', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (192, 'Auria Errett', 'F', '1968-11-14', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (193, 'Jefferey Killimister', 'M', '1969-11-17', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (194, 'Evangelia Runnett', 'F', '1991-10-14', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (195, 'Millicent Dignan', 'F', '1970-11-14', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (196, 'Mortie Blumer', 'M', '1962-03-14', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (197, 'Marley Sanchez', 'F', '1960-06-10', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (198, 'Arline Filipponi', 'F', '1996-07-10', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (199, 'Andrew Wisker', 'M', '1968-10-17', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (200, 'Kylie Gutridge', 'M', '1971-09-17', 'São Bento');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (201, 'Prue Slocumb', 'F', '1962-05-02', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (202, 'Marybeth Quimby', 'F', '1996-12-29', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (203, 'Loy Shucksmith', 'M', '1978-10-02', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (204, 'Shelley Lie', 'M', '1974-12-07', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (205, 'Elsa Clynman', 'F', '1988-01-15', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (206, 'Yance McHan', 'M', '1987-07-03', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (207, 'Staford Catlette', 'M', '1968-10-30', 'Vila Meriti');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (208, 'Moyra Brothers', 'F', '1991-06-22', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (209, 'Monro Lithgow', 'M', '1980-02-09', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (210, 'Alla O''Grogane', 'F', '1996-08-21', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (211, 'Ulrika Springthorpe', 'F', '1990-09-11', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (212, 'Blake Le Blond', 'F', '1971-07-02', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (213, 'Emerson Laurent', 'M', '2000-02-17', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (214, 'Yuri Ruprecht', 'M', '1981-12-16', 'Bar dos Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (215, 'Andie Kenrack', 'F', '1976-02-03', 'Pauliceia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (216, 'Hilde Etheredge', 'F', '1988-04-16', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (217, 'Penny Elsip', 'F', '1978-09-06', 'Jardim Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (218, 'Sheilakathryn MacAloren', 'F', '2000-01-29', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (219, 'Angie McCahey', 'F', '1985-10-12', 'Parque Felicidade');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (220, 'Raul Vollam', 'M', '1969-08-20', 'São Bento');
